databases:
  - name: wanderlustdb
    plan: free
    databaseName: wanderlust
    user: wanderlust

services:
  - type: web
    plan: free
    name: wanderlust
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    previews:
      generation: automatic
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wanderlustdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
