# Generated by Django 5.1.6 on 2025-03-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='mapbox_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
