# Generated by Django 5.1.6 on 2025-05-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='mapbox_id',
        ),
    ]
